const ContactActionTypes = {
    GET_CONTACTS: 'GET_CONTACTS',
    ADD_CONTACT_START: 'ADD_CONTACT_START',
    ADD_CONTACT_SUCCESS: 'ADD_CONTACT_SUCCESS',
    ADD_CONTACT_FAILURE: 'ADD_CONTACT_FAILURE',
    DELETE_CONTACT: 'DELETE_CONTACT',
    SET_CURRENT_CONTACT: 'SET_CURRENT_CONTACT',
    CLEAR_CURRENT_CONTACT: 'CLEAR_CURRENT_CONTACT',
    UPDATE_CONTACT: 'UPDATE_CONTACT',
    FILTER_CONTACTS: 'FILTER_CONTACTS',
    CLEAR_FILTER: 'CLEAR_FILTER',
};

export default ContactActionTypes;